function run(Event_list, max_time, log_file, simID)

% global node mac_status;
global current_time;

global rpktsend;
global rpktrecv; 
global rEnergy;
rpktsend=0;
rpktrecv=0; 
rEnergy=0;
ppktsend=0;
ppktrecv=0;
pEnergy=0;

% Event driven simulation loop
while 1
    [min_instant, min_index] = min([Event_list(:).instant]);
    if isempty(min_instant)
        break;
    end
    if min_instant > max_time
        break;
    end
    
    
    [NewEvents, rpktsend, rpktrecv, rEnergy]= action(Event_list(min_index), log_file, simID,ppktsend, ppktrecv, pEnergy);      % Get new events from executing the latest 'action'
    current_time = min_instant;
   
    Event_list(min_index) = [];                     % Delete the latest event which has been just executed.

    ppktsend=rpktsend;
    ppktrecv=rpktrecv;
    pEnergy=rEnergy;
    
    
    %--kabeer copy previous status in next event
%     [min_instant, min_index] = min([Event_list(:).instant]);
%     if isempty(min_instant)
%         break;
%     end
%     if min_instant > max_time
%         break;
%     end
% disp('hello');
% [rpktsend rpktrecv rEnergy]
% 
    
%     Event_list(min_index).pktsend=rpktrecv;
%     Event_list(min_index).pktrecv=rpktrecv; 
%     Event_list(min_index).Energy=rEnergy;

%     Event_list(min_index).pktsend=NewEvents.pktsend; 
%     Event_list(min_index).pktrecv=NewEvents.pktrecv; 
%     Event_list(min_index).Energy=NewEvents.Energy;
    %--
    Event_list = [NewEvents; Event_list];   % Append new events generated by executing the latest event
end

return;